import os
import sys
from pathlib import Path
from openai import OpenAI
from datetime import datetime
import dotenv
import json
import yaml
import re
import pandas as pd
from json_repair import repair_json
from time import sleep

from engine.util import (
    get_logger,
    format_message,
    OUTPUT_DIR,
    ENGINE_LOG_DIR,
    load_config,
)
logger = get_logger()
 
from judge.prompt.builder.prompt_builder import PromptBuilder 

dotenv.load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY")
)


def clean_json_markdown(text: str) -> str:
    text = re.sub(r'^```json\s*\n?', '', text.strip())
    text = re.sub(r'^```\s*\n?', '', text.strip())
    text = re.sub(r'\n?```\s*$', '', text.strip())
    return text.strip()

def judge_recomendations(recomendations:pd.DataFrame, metrics:dict,cluster_info:list) -> pd.DataFrame:
    migrations = get_migrations(recomendations)
    if len(migrations) == 0:
        logger.info(msg=format_message("No one migration was recommended, The judge will return recomendations of ai-engine",bold=False))
        return recomendations
    
    prompt_builder = PromptBuilder(migrations,metrics,cluster_info)
    prompt = prompt_builder.build_prompt()
    output = ""

    try:
        output = call_llm(prompt=prompt)
    except Exception as e:
        logger.error(format_message(f"Error calling LLM: {str(e)}. Trying to call again", color='RED', bold=True))
        sleep(3)
        try:
            output = call_llm(prompt=prompt)
        except Exception as e:
            logger.error(format_message(f"Error calling LLM: {str(e)}. The judge will return the recomendations generated by ai-engine", color='RED', bold=True))
            return pd.DataFrame(recomendations)

    output = clean_json_markdown(output)
    
    try:
        output = json.loads(output)
    except Exception as e:
        logger.error(format_message(f"Response from LLM was truncated, The judge will try to fix it ❌",color='RED',bold=True))
        dados = ""
        json_repaired = repair_json(output)

        try:
            dados = json.loads(json_repaired)
        except Exception as e:
            logger.error(format_message(f"It was not possible to fix the recommendations. The judge will return recomendations generated by ai-engine",color='RED',bold=True,icon="❌"))
            return pd.DataFrame(recomendations)
        
        valid_recomendations = return_valid_recomendations(dados)
        qtd_valids = len(valid_recomendations)
        qtd_generated = len(recomendations)
        percent = qtd_valids / qtd_generated

        if percent > 0.5:
            output = valid_recomendations
            logger.info(format_message(f"{percent*100:.2f} recomendations were fixed, its will be sent to the actuator",color='BLUE',bold=True))

        else:
            logger.error(format_message(f"only {percent*100:.2f} were fixeds, but there aren’t enough to apply.",color='RED',bold=True))
            return pd.DataFrame(recomendations)

            
    filtered_recomendations = filter_approved_recomendations(output)
    log_recomendations(filtered_recomendations)

    return pd.DataFrame(filtered_recomendations)


def filter_approved_recomendations(output:dict) -> list:
    final_recomendations = []
    for recomendation in output["validated_recommendations"]:
        if not has_atributes(recomendation):continue
        if recomendation["llm_status"] == 0: continue

        keep_in_cluster = recomendation["destination_cluster"] == recomendation["origin_cluster"]

        if keep_in_cluster: continue


        current_recomendation = {}
        current_recomendation["workload_id"] = recomendation["workload_id"]
        current_recomendation["kind"] = "deployment"

        current_recomendation["label"] = recomendation["destination_cluster"]

        current_recomendation["reason"] = recomendation["llm_reasoning"]

        final_recomendations.append(current_recomendation)

    return final_recomendations


def call_llm(prompt: str) -> str:
    messages = [{"role": "user", "content": prompt}]

    try:
        response = client.chat.completions.create(
            model="bytedance-seed/seed-1.6-flash",
            messages=messages,
            max_completion_tokens=16000
        )
        
        # Extract and return the content from the response
        return response.choices[0].message.content
    
    except Exception as e:
        logger.error(format_message(f"Error calling LLM: {str(e)}", color='RED', bold=True))
        raise
    
def log_recomendations(recomendations:list):
    logger.info(format_message(
        f"The judge approved {len(recomendations)} migrations",
        color='BLUE',bold=True,icon="👨‍⚖️"))
    
    clusters = {"public":"private","private":"public"}
    for recomendation in recomendations:

        destination_cluster =  "public" if recomendation["label"] == 1 else "private"
        logger.info(format_message(
        f"workload {recomendation["workload_id"]} migration from {clusters[destination_cluster]} to {destination_cluster} -> {recomendation["reason"]}",
        color='BLUE',bold=False,icon="👨‍⚖️"))

def has_atributes(recomendation:dict) -> bool:
    keys = recomendation.keys()

    if "workload_id" not in keys:
        return False
    if "destination_cluster" not in keys:
        return False
    if "origin_cluster" not in keys:
        return False
    if "llm_status" not in keys:
        return False
    if "llm_reasoning" not in keys:
        return False

    return True

def return_valid_recomendations(recomendations:list) -> list:
    valid_recomendations = []

    for recomendation in recomendations:
        if has_atributes(recomendation):
            valid_recomendations.append(recomendation)

    return valid_recomendations

def get_migrations(workloads:pd.DataFrame) -> pd.DataFrame:
    workloads = workloads.to_dict(orient="records")
    output = []
    for workload in workloads:
        if workload["label"] == 1:
            output.append(workload)

    return output