data:
  input_json: ../../data/output/monitor_outputs.json

ai:
  model: gemini

# Diretórios para diferentes componentes do sistema
paths:
  models_dir: ai-engine/model-pipeline/models
  output_dir: ai-engine/data/output
  log_dir: ai-engine/logs

logging:
  level: DEBUG
  file: ai_engine.log

api-key:
  google: AIzaSyBiAqFQ5cI0e9ovCP86U6uw0U8_iij5A_c

monitor:
  host: 0.0.0.0
  port: 8082
  route: metrics

actuator:
  host: 0.0.0.0
  port: 8084
  route: apply

server:
  host: 0.0.0.0
  port: 8083
  route: start/stop
  reload: false
  