FROM python:3.12.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV MODE=cli

# Environment variables from .env
ENV GOOGLE_API_KEY=""
ENV OPENAI_API_KEY=""
ENV OPENROUTER_API_KEY=""
ENV GROQ_API_KEY=""
ENV ANTHROPIC_API_KEY=""
ENV LANGCHAIN_TRACING_V2=""
ENV LANGCHAIN_API_KEY=""
ENV LANGCHAIN_PROJECT=""
ENV LANGCHAIN_ENDPOINT=""

# Run in CLI mode
ENTRYPOINT ["python", "cli.py"]
