FROM python:3.12.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV MODE=api
ENV PYTHONPATH=/app


EXPOSE 8083

# Run in API mode
CMD ["python", "api.py"]