data:
  input_json: monitor_outputs_v2.json

ai:
  model: gemini

# Diretórios para diferentes componentes do sistema
paths:
  models_dir: ai-engine/model-pipeline/models
  output_dir: ai-engine/output
  log_dir: ai-engine/logs

logging:
  level: INFO
  file: ai_engine.log

api-key:
  google: KEY_VALUE
