data:
  input_json: monitor_outputs_v2.json

ai:
  model: gemini

# Diretórios para diferentes componentes do sistema
paths:
  models_dir: ../model-pipeline/models
  actuator_dir: ../../actuator
  log_dir: ../logs

logging:
  level: INFO
  file: ai_engine.log

api-key:
  google: KEY_VALUE
